project_id = "ahksxziueqkacyaqtgeu"

[functions.confirm-user]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false

[functions.backfill-display-names]
verify_jwt = false

[functions.generate-ping-question]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.parse-resume]
verify_jwt = true

[functions.get-resume]
verify_jwt = false

